// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function LoadDomains() {
  return window['go']['main']['App']['LoadDomains']();
}

export function ManageService(arg1) {
  return window['go']['main']['App']['ManageService'](arg1);
}

export function OpenHomePage() {
  return window['go']['main']['App']['OpenHomePage']();
}

export function OpenLogFolder() {
  return window['go']['main']['App']['OpenLogFolder']();
}

export function SaveDomains(arg1) {
  return window['go']['main']['App']['SaveDomains'](arg1);
}

export function ToggleLogging(arg1) {
  return window['go']['main']['App']['ToggleLogging'](arg1);
}

export function ToggleSteamProxy(arg1) {
  return window['go']['main']['App']['ToggleSteamProxy'](arg1);
}
