// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig():Promise<Record<string, boolean>>;

export function LoadDomains():Promise<string>;

export function ManageService(arg1:string):Promise<string>;

export function OpenHomePage():Promise<void>;

export function OpenLogFolder():Promise<void>;

export function SaveDomains(arg1:string):Promise<string>;

export function ToggleLogging(arg1:boolean):Promise<string>;

export function ToggleSteamProxy(arg1:boolean):Promise<string>;
